using System.Text.Json;
using KspNavComputer.Core.Bodies;
using KspNavComputer.Core.Maneuver;
using KspNavComputer.Core.Transfer;

namespace KspNavComputer.Core.Tests;

/// <summary>
/// Cross-validates TransferComputer.ComputeRoundTrip against pre-computed
/// reference values generated by alexmoon's Launch Window Planner (LWP).
///
/// Reference data: tests/Core/Data/reference-round-trips.json
/// Generator script: scripts/generate-round-trip-references.js
///
/// Each reference case is the sum of two independent LWP one-way transfers:
///   outbound (origin → dest) + return (dest → origin).
/// Tolerance: ±1 % per leg on total Δv (same as one-way reference tests).
/// </summary>
public sealed class ReferenceRoundTripTests
{
    private sealed record ReferenceCase(
        string Description,
        string Origin,
        string Destination,
        double DepartureUT,
        double OutboundTimeOfFlight,
        double StayDuration,
        double ReturnTimeOfFlight,
        double ParkingOrbitAltitude,
        double DestinationOrbitAltitude,
        double OutboundEjectionDeltaV,
        double OutboundInsertionDeltaV,
        double OutboundTotalDeltaV,
        double ReturnEjectionDeltaV,
        double ReturnInsertionDeltaV,
        double ReturnTotalDeltaV,
        double TotalDeltaV,
        double? OutboundEjectionAngleDeg,
        double? OutboundEjectionInclinationDeg,
        double? ReturnEjectionAngleDeg,
        double? ReturnEjectionInclinationDeg
    );

    private static IReadOnlyList<ReferenceCase> LoadCases()
    {
        var dataPath = Path.Combine(
            AppContext.BaseDirectory,
            "Data",
            "reference-round-trips.json"
        );
        var json    = File.ReadAllText(dataPath);
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return JsonSerializer.Deserialize<List<ReferenceCase>>(json, options)!;
    }

    public static IEnumerable<object?[]> ReferenceCaseData()
    {
        foreach (var c in LoadCases())
            yield return [
                c.Description,
                c.Origin, c.Destination,
                c.DepartureUT, c.OutboundTimeOfFlight, c.StayDuration, c.ReturnTimeOfFlight,
                c.ParkingOrbitAltitude, c.DestinationOrbitAltitude,
                c.OutboundEjectionDeltaV, c.OutboundInsertionDeltaV, c.OutboundTotalDeltaV,
                c.ReturnEjectionDeltaV,   c.ReturnInsertionDeltaV,   c.ReturnTotalDeltaV,
                c.TotalDeltaV,
                (object?)c.OutboundEjectionAngleDeg, (object?)c.OutboundEjectionInclinationDeg,
                (object?)c.ReturnEjectionAngleDeg,   (object?)c.ReturnEjectionInclinationDeg
            ];
    }

    [Theory]
    [MemberData(nameof(ReferenceCaseData))]
    public void RoundTrip_MatchesLwpReference_WithinOnePct(
        string description,
        string origin, string destination,
        double departureUT, double outboundTof, double stayDuration, double returnTof,
        double parkAlt, double destAlt,
        double expOutEject, double expOutInsert, double expOutTotal,
        double expRetEject, double expRetInsert, double expRetTotal,
        double expTotal,
        double? expOutEjectAngle, double? expOutEjectInc,
        double? expRetEjectAngle, double? expRetEjectInc)
    {
        _ = description;

        var parameters = new RoundTripParameters(
            Origin:               BodyDatabase.All[origin],
            Destination:          BodyDatabase.All[destination],
            DepartureUT:          departureUT,
            OutboundTimeOfFlight: outboundTof,
            StayDuration:         stayDuration,
            ReturnTimeOfFlight:   returnTof,
            OriginOrbit:          new ParkingOrbit(Altitude: parkAlt),
            DestinationOrbit:     new ParkingOrbit(Altitude: destAlt)
        );

        var result = TransferComputer.ComputeRoundTrip(parameters);

        const double tol = 0.01; // 1 %

        // Outbound leg
        AssertWithinPct(expOutEject,  result.Outbound.Ejection.DeltaV,  tol, $"{description} outbound ejection");
        AssertWithinPct(expOutInsert, result.Outbound.Insertion.DeltaV, tol, $"{description} outbound insertion");
        AssertWithinPct(expOutTotal,  result.Outbound.TotalDeltaV,     tol, $"{description} outbound total");

        // Return leg
        AssertWithinPct(expRetEject,  result.Return.Ejection.DeltaV,    tol, $"{description} return ejection");
        AssertWithinPct(expRetInsert, result.Return.Insertion.DeltaV,   tol, $"{description} return insertion");
        AssertWithinPct(expRetTotal,  result.Return.TotalDeltaV,       tol, $"{description} return total");

        // Mission total
        AssertWithinPct(expTotal, result.TotalDeltaV, tol, $"{description} mission total");

        // Ejection angle and inclination — ±0.5° tolerance
        if (expOutEjectAngle.HasValue)
        {
            Assert.NotNull(result.Outbound.Ejection.Ejection);
            AssertWithinDeg(expOutEjectAngle.Value, result.Outbound.Ejection.Ejection!.AngleDeg,       0.5, $"{description} outbound ejection angle");
            AssertWithinDeg(expOutEjectInc!.Value,  result.Outbound.Ejection.Ejection!.InclinationDeg, 0.5, $"{description} outbound ejection inc");
        }
        if (expRetEjectAngle.HasValue)
        {
            Assert.NotNull(result.Return.Ejection.Ejection);
            AssertWithinDeg(expRetEjectAngle.Value, result.Return.Ejection.Ejection!.AngleDeg,       0.5, $"{description} return ejection angle");
            AssertWithinDeg(expRetEjectInc!.Value,  result.Return.Ejection.Ejection!.InclinationDeg, 0.5, $"{description} return ejection inc");
        }
    }

    private static void AssertWithinPct(double expected, double actual, double pct, string label)
    {
        double relErr = Math.Abs(actual - expected) / expected;
        Assert.True(
            relErr <= pct,
            $"{label}: expected {expected:F2} m/s, got {actual:F2} m/s " +
            $"(relative error {relErr * 100:F3} % > tolerance {pct * 100:F1} %)");
    }

    private static void AssertWithinDeg(double expected, double actual, double toleranceDeg, string label)
    {
        double err = Math.Abs(actual - expected);
        Assert.True(
            err <= toleranceDeg,
            $"{label}: expected {expected:F4}°, got {actual:F4}° (error {err:F4}° > tolerance {toleranceDeg}°)");
    }
}
