using System.Text.Json;
using KspNavComputer.Core.Bodies;
using KspNavComputer.Core.Transfer;

namespace KspNavComputer.Core.Tests;

/// <summary>
/// Cross-validates TransferComputer against pre-computed reference values
/// generated by alexmoon's Launch Window Planner (LWP).
///
/// Reference data: tests/Core/Data/reference-transfers.json
/// Generator script: scripts/generate-reference-transfers.js
///
/// Tolerance: ±1 % on total Δv. This covers:
///   - Minor GM differences between LWP (mass × G) and our BodyDatabase
///     (KSP direct values); the systematic error is &lt;0.01 %.
///   - Floating-point accumulation in different Lambert formulations.
/// The SOI-boundary ejection/insertion correction is shared by both
/// implementations; any regression there will fail these tests.
/// </summary>
public sealed class ReferenceTransferTests
{
    private sealed record ReferenceCase(
        string Description,
        string Origin,
        string Destination,
        double DepartureUT,
        double TimeOfFlight,
        double ParkingOrbitAltitude,
        double DestinationOrbitAltitude,
        double EjectionDeltaV,
        double InsertionDeltaV,
        double TotalDeltaV
    );

    private static IReadOnlyList<ReferenceCase> LoadCases()
    {
        var dataPath = Path.Combine(
            AppContext.BaseDirectory,
            "Data",
            "reference-transfers.json"
        );

        var json = File.ReadAllText(dataPath);
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return JsonSerializer.Deserialize<List<ReferenceCase>>(json, options)!;
    }

    public static IEnumerable<object[]> ReferenceCaseData()
    {
        foreach (var c in LoadCases())
            yield return [c.Description, c.Origin, c.Destination, c.DepartureUT,
                          c.TimeOfFlight, c.ParkingOrbitAltitude,
                          c.DestinationOrbitAltitude, c.TotalDeltaV,
                          c.EjectionDeltaV, c.InsertionDeltaV];
    }

    [Theory]
    [MemberData(nameof(ReferenceCaseData))]
    public void TotalDeltaV_MatchesLwpReference_WithinOnePct(
        string description,
        string origin, string destination,
        double departureUT, double tof,
        double parkAlt, double destAlt,
        double expectedTotal, double expectedEjection, double expectedInsertion)
    {
        _ = description; // surfaced in test name via MemberData label

        var parameters = new TransferParameters(
            Origin:          BodyDatabase.All[origin],
            Destination:     BodyDatabase.All[destination],
            DepartureUT:     departureUT,
            TimeOfFlight:    tof,
            OriginOrbit:     new ParkingOrbit(Altitude: parkAlt),
            DestinationOrbit: new ParkingOrbit(Altitude: destAlt)
        );

        var result = TransferComputer.Compute(parameters);

        const double tolerancePct = 0.01; // 1 %
        AssertWithinPct(expectedTotal,     result.TotalDeltaV,     tolerancePct, "TotalDeltaV");
        AssertWithinPct(expectedEjection,  result.EjectionDeltaV,  tolerancePct, "EjectionDeltaV");
        AssertWithinPct(expectedInsertion, result.InsertionDeltaV, tolerancePct, "InsertionDeltaV");
    }

    private static void AssertWithinPct(double expected, double actual, double pct, string label)
    {
        double relErr = Math.Abs(actual - expected) / expected;
        Assert.True(
            relErr <= pct,
            $"{label}: expected {expected:F2} m/s, got {actual:F2} m/s " +
            $"(relative error {relErr * 100:F3} % > tolerance {pct * 100:F1} %)");
    }
}
